apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/iammuho/spark-test.git'
    path: Custom_folder/k8s
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: spark-app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true